console.log("My last name is Li");
var first="Evan";
console.log(first);
var second="Li";
console.log(second);
var fullname=first.concat(second);
console.log(fullname);
var length=fullname.length;
console.log(length);
var sentence="This is an example";
var sentence1=sentence.replace("example", "example as well.");
console.log(sentence1);
var lowercase=fullname.toLowerCase();
console.log(lowercase);
var uppercase=fullname.toUpperCase();
console.log(uppercase);
var a=Math.sqrt(625);
console.log(a);
var maxnumber=Math.max(10, 5);
console.log(maxnumber);
var minnumber=Math.min(10, 5);
console.log(minnumber);
var power=Math.pow(37, 25);
console.log(power);